Repository YJU-OKURA/project_minori-gin-deployment-repo, pull requests merged in 2024-11, with the labels that each got.

#350 LINEログインの実装
  controllers/line_auth_controller.go
  main.go
  repositories/line_auth_repository.go
  services/line_auth_services.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 🆗 safe

#352 ♻️ refactor: 出席管理システムの機能強化と CSID ベースの追跡機能を実装
  controllers/attendance_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/attendance_repository.go
  repositories/class_schedule_repository.go
  services/attendance_service.go
Labels: ⏰ P1, 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#353 ♻️ refactor: 出席管理システムの機能強化と CSID ベースの追跡機能を実装
  controllers/attendance_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#354 出席管理APIのルート構造改善とSwagger文書の強化
  controllers/attendance_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#357 N+1問題を解決するためのAttendance統計メソッドの修正
  repositories/attendance_repository.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#358 ♻️ refactor: Enhance attendance preload relationships in repository
  repositories/attendance_repository.go
  services/attendance_service.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#360 出席カウントのデフォルト値を0に設定する
  controllers/attendance_controller.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#361 プロフィール写真
  repositories/line_auth_repository.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🥰 Accessibility, 🆗 safe
