Repository YJU-OKURA/project_minori-gin-deployment-repo, pull requests merged in 2024-02, with the labels that each got.

#8 `gin`と`mysql`の`Docker`環境設定
  docker-compose.yml
  docker/go/Dockerfile
  docker/mysql/Dockerfile
  docker/mysql/env
Labels: ✨ Feature, ⏰ P2

#6 プロジェクト初期設計：リポジトリパターンとレイヤードアーキテクチャの適用
  .env.example
  .gitignore
  constants/error_messages.go
  constants/http_status_codes.go
  constants/roles.go
  controllers/user_controller.go
  dto/user_dto.go
  infra/db.go
  infra/initializer.go
  main.go
  makeFile
  middlewares/authentication_middleware.go
  middlewares/error_handling_middleware.go
  middlewares/logging_middleware.go
  migration/main.go
  migration/migrations/1_users.down.sql
  migration/migrations/1_users.up.sql
  models/user.go
  repositories/user_repository.go
  services/user_service.go
  utils/date_utils.go
  utils/string_utils.go
  utils/validation_utils.go
Labels: ⏰ P1, ⚙ Setting

#10 GitHub Actionsの自動レビュワーと自動アサインのロジック改善
  .github/auto_assign.yml
  .github/workflows/auto-issue-assign.yml
  .github/workflows/auto-member.yml
Labels: ⚙ Setting, ⏰ P3, 🐞 BugFix, 🔨 Refactor

#11 GitHub Actionsワークフローの改善: トリガーイベントとトークンの変更
  .github/workflows/openai_code_review.yml
Labels: ⚙ Setting, ⏰ P3, 🐞 BugFix, 🔨 Refactor

#13 GitHub ActionsでChatGPT-CodeReviewのバージョンをv1.0.11に更新
  .github/workflows/openai_code_review.yml
Labels: ⚙ Setting, ⏰ P3, 🐞 BugFix, 🔨 Refactor

#12 GinフレームワークにSwaggerを統合してAPIドキュメンテーションを改善
  .air.toml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
Labels: ⚙ Setting, ⏰ P3, ✨ Feature, 📬 API, 📃 Docs

#14 Swaggerドキュメントのパス問題を解決するためのモジュール名の変更
  go.mod
Labels: ⚙ Setting, ⏰ P3, 🐞 BugFix, 📬 API

#17 PRテンプレートから不要な部分を削除
  .github/pull_request_template.md
Labels: ⏰ P3, 📃 Docs

#19 CIプロセスとDockerデプロイメントの設定を追加
  .github/workflows/ci.yml
Labels: 🌏 Deploy, ⏰ P2

#21 Trelloリンク連動機能の追加によるGitHub課題テンプレートの改善
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: ⚙ Setting, ⏰ P3, 📃 Docs

#23 Trelloリンク連動機能の追加によるGitHub PRテンプレートの改善
  .github/pull_request_template.md
Labels: ⚙ Setting, ⏰ P3, 📃 Docs

#26 CIワークフローにおけるイメージタグの改善
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2

#27 モデル実装とマイグレーションロジックの追加、及び不要なファイルの削除
  .env.example
  main.go
  migration/main.go
  migration/migration.go
  migration/migrations/1_users.down.sql
  migration/migrations/1_users.up.sql
  models/attendance.go
  models/class.go
  models/class_user.go
  models/group_board.go
  models/group_code.go
  models/group_schedule.go
  models/role.go
  models/user.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor

#29 メイン関数の効率化とロジックの改善
  main.go
Labels: ⏰ P3, 🔨 Refactor

#31 EC2への自動デプロイ機能とCIワークフローの改善
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ⏰ P1, 🌏 Deploy, ✨ Feature, 🆗 safe

#35 エラーメッセージとHTTPステータスコードの一元管理の実装
  constants/error_messages.go
  constants/http_status_codes.go
Labels: ⚙ Setting, ⏰ P3, ✨ Feature, 📬 API, 🆗 safe

#36 GitHub Actions Docker CIワークフローの最適化
  .github/workflows/ci.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🆗 safe

#37 データベース接続とマイグレーションの問題解決
  main.go
  migration/migration.go
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#38 GitHub ActionsのDockerイメージタグ比較ロジック削除
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#40 グループコード機能の実装とドキュメンテーションの更新
  .github/workflows/ci.yml
  controllers/group_code_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/group_code_request.go
  go.mod
  go.sum
  main.go
  repositories/group_code_repository.go
  services/group_code_service.go
  tests/group_code_controller_test.go
Labels: ⏰ P1, ⚙ Setting, 🌏 Deploy, ✅ Test, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#41 不使用Dockerfileおよびdocker-compose.ymlの削除
  .gitignore
  docker-compose.yml
  docker/go/Dockerfile
  docker/mysql/Dockerfile
  docker/mysql/env
Labels: ⚙ Setting, ⏰ P3, 🔨 Refactor

#43 モデルカラムのアノテーションを更新してコードの明確性向上
  migration/migration.go
  models/attendance.go
  models/class.go
  models/class_user.go
  models/group_board.go
  models/group_schedule.go
Labels: 🔨 Refactor, ⏰ P2, 🆗 safe

#44 GroupCodeモデルの改善とRESTful APIの適用
  controllers/group_code_controller.go
  dto/group_code_dto.go
  models/group_code.go
  services/group_code_service.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#47 .air.tomlを.gitignoreに追加
  .air.toml
  .gitignore
Labels: ⚙ Setting, ⏰ P2

#48 グループボードのCRUD機能の実装
  constants/error_messages.go
  controllers/group_board_controller.go
  controllers/response_handlers.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/group_board_dto.go
  go.mod
  go.sum
  main.go
  repositories/group_board_repository.go
  services/errors.go
  services/group_board_service.go
  utils/uploader.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs

#49 エラーメッセージとHTTPステータスコードの構造を整理
  constants/error_messages.go
  constants/http_status_codes.go
Labels: ⚙ Setting, 🔨 Refactor
