Repository YJU-OKURA/project_minori-gin-deployment-repo, pull requests merged in 2024-03, with the labels that each got.

#54 自己ホスト型ランナーを使用したEC2へのデプロイ機能の実装
  .github/workflows/cd.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#53 クラスユーザーとロール管理の機能強化
  constants/error_messages.go
  controllers/class_board_controller.go
  controllers/class_code_controller.go
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_board_dto.go
  dto/class_user_dto.go
  models/class_board.go
  models/class_code.go
  models/class_schedule.go
  repositories/class_user_repository.go
  repositories/role_repository.go
  services/class_board_service.go
  services/class_user_service.go
  utils/uploader.go
Labels: ⏰ P1, 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#55 クラススケジュール検索機能の追加とクラスボード画像アップロード処理の改善
  controllers/class_board_controller.go
  controllers/class_schedule_controller.go
  dto/class_schedule_dto.go
  main.go
  repositories/class_schedule_repository.go
  services/class_schedule_service.go
  tests/group_code_controller_test.go
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, ✅ Test, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#56 EC2インスタンスへのDockerデプロイメントプロセスの自動化
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#58 GitHub Actionsのワークフローに環境変数を追加
  .github/workflows/ci.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🆗 safe

#59 GitHub ActionsとDockerfileに環境変数を統合
  .github/workflows/ci.yml
  Dockerfile
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#60 出席管理機能の実装とルーター設定
  controllers/attendance_controller.go
  main.go
  models/attendance.go
  repositories/attendance_repository.go
  services/attendance_service.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🆗 safe

#61 出席管理システムにクラススケジュール機能を統合するための改善
  controllers/attendance_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  models/attendance.go
  repositories/attendance_repository.go
  services/attendance_service.go
Labels: ⏰ P1, 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#62 環境設定とDockerセットアップの改善
  .github/workflows/ci.yml
  Dockerfile
  main.go
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#63 EC2への自動デプロイワークフローの更新
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🆗 safe

#64 EC2自動デプロイメントのGitHub Actionsワークフローを更新
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#65 AWS CLIコマンドの修正によるGitHub Actionsワークフローの改善
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🆗 safe

#67 APIドキュメンテーションとコード構造の全面的な改善
  constants/error_messages.go
  controllers/attendance_controller.go
  controllers/class_board_controller.go
  controllers/class_code_controller.go
  controllers/class_schedule_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  migration/migration.go
  repositories/attendance_repository.go
  repositories/class_board_repository.go
  repositories/class_code_repository.go
  repositories/class_schedule_repository.go
  repositories/class_user_repository.go
  repositories/role_repository.go
  services/attendance_service.go
  services/class_board_service.go
  services/class_code_service.go
  services/class_schedule_service.go
  services/class_user_service.go
Labels: ⏰ P3, 🔨 Refactor, 📃 Docs, 🆗 safe

#70 AWS EC2インスタンスのデプロイ自動化の改善
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#69 GinフレームワークにCORSサポートを追加
  go.mod
  go.sum
  main.go
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 💻 CrossBrowsing, 📬 API, 🆗 safe

#73 ClassUserControllerの機能拡張とSwaggerドキュメントの更新
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#76 ローカル開発環境用の環境変数読み込み機能追加
  main.go
Labels: ⚙ Setting, ⏰ P3, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#77 Swaggerのドキュメントタグ更新
  controllers/attendance_controller.go
  controllers/class_board_controller.go
  controllers/class_code_controller.go
  controllers/class_schedule_controller.go
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⏰ P3, 📃 Docs, 🆗 safe

#79 ミドルウェアの統合とドキュメント更新
  controllers/attendance_controller.go
  controllers/class_board_controller.go
  controllers/class_schedule_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  middlewares/authentication_middleware.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#74 Googleソーシャルログイン機能の実装
  controllers/google_auth_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/google_auth_dto.go
  go.mod
  go.sum
  main.go
  models/user.go
  repositories/google_auth_repository.go
  services/google_auth_service.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 🆗 safe

#84 不必要なパッケージの削除と`go.mod` と `go.sum` ファイルのパッケージ設定を更新
  go.mod
  go.sum
Labels: ⏰ P1, ⚙ Setting, 🐞 BugFix

#85 CheckSecretExistsメソッドのnilと空文字列チェックの改善
  services/class_code_service.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#87 クラス内でニックネーム変更APIの実装
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ⏰ P3, ✨ Feature, 📬 API, 🆗 safe

#89 クラス作成機能の実装
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_dto.go
  main.go
  repositories/class_repository.go
  services/class_service.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 📃 Docs, 🆗 safe

#91 特定ユーザーが登録しているクラス情報を確認できるAPIの開発
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_user_dto.go
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#93 📝 README.mdファイルの更新とドキュメンテーションの改善
  README.md
Labels: ⏰ P3, 📃 Docs

#95 `CheckSecretExists`メソッドの404エラーハンドリング修正
  controllers/class_code_controller.go
  services/class_code_service.go
Labels: 🐞 BugFix, 🔨 Refactor, ⏰ P2, 🆗 safe

#97 ユーザー申請中クラス情報取得ロジックの実装
  constants/error_messages.go
  controllers/class_code_controller.go
  controllers/user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  models/role.go
  repositories/user_repository.go
  services/class_code_service.go
  services/user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#98 📝 README.mdにAPIサーバーの機能説明を追加
  README.md
Labels: ⏰ P3, 📃 Docs

#100 Googleログインエラーの修正
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🆗 safe

#102 CORS設定問題の解決に関するPR
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#103 Next.jsローカル環境のためのCORS設定の変更
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#105 ClassCodeServiceのエラー処理とコードリファクタリングの改善
  services/class_code_service.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#106 Googleログインエラーの修正
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🆗 safe

#107 Google認証コールバックの実装の取り消し
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#109 GoogleAuthControllerの修正
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🆗 safe

#110 Google認証コールバックの修正
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🆗 safe

#112 クラスコード検証ロジックの修正
  controllers/class_code_controller.go
  services/class_code_service.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#113 class_code_controller の型変換問題の修正
  controllers/class_code_controller.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#114 GoogleAuthControllerのログインコールバックメソッドを以前のバージョンに復旧
  controllers/google_auth_controller.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#115 CORSポリシーの設定拡大
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#116 CORSポリシーの一時的な全許可設定
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#117 CORSポリシーの特定オリジンへの制限
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#118 CORS設定の変更によるオリジンアクセスの拡張と資格情報設定の更新
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#119 CORS設定の再制限と資格情報ポリシーの更新
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#120 CORS設定の動的対応に関する改善
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#121 CORS設定の静的設定への変更
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#122 APIルートのトレーリングスラッシュ削除によるCORS問題解決
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#123 CORSポリシーの改善によるアクセス制御エラーの解決
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#125 GetUserClasses関数のSelectメソッド引数にclass_users.role_idを追加
  dto/class_user_dto.go
  repositories/class_user_repository.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#127 ログイン後のメインページへのリダイレクト機能を追加
  controllers/google_auth_controller.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#128 CORS設定を限定的に変更してクラスボードのエラーを解決
  main.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🥰 Accessibility, 🆗 safe

#131 クラス内ユーザー情報確認機能の追加
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_user_dto.go
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🆗 safe
