Repository YJU-OKURA/project_minori-gin-deployment-repo, pull requests merged in 2024-04, with the labels that each got.

#134 クラス掲示板にページネーション機能の追加
  controllers/class_board_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  repositories/class_board_repository.go
  services/class_board_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#135 GoogleAuthCallbackの変更
  constants/http_status_codes.go
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#136 チャット機能の統合とドキュメント更新
  constants/error_messages.go
  constants/http_status_codes.go
  controllers/chat_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/chat_service.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 📃 Docs, 🆗 safe

#137 SameSite クッキー設定の追加
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#138 Redisをプロジェクトに導入してチャット機能を強化
  go.mod
  go.sum
Labels: ⚙ Setting, ⏰ P3, 🆗 safe

#140 お気に入りクラス機能の実装とSwagger文書の更新
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#142 特定ユーザークラス取得機能の実装
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🆗 safe

#144 ユーザーの役割に基づくクラス情報取得機能の追加
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#145 ユーザーのロールに基づくクラス情報取得のエラーハンドリングを改善
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#147 ユーザーとクラスに関連する情報の取得機能とSwagger文書の更新
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#148 クッキー設定のためSecure属性を変更
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#150 Dockerビルドプロセス中のモジュール依存関係エラーの解決
  go.mod
  go.sum
Labels: ⏰ P1, ⚙ Setting, 🌏 Deploy, 🐞 BugFix, 🆗 safe

#153 クラスメンバーのロジック改善とRoleモデル更新
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  models/role.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#155 クラス情報取得APIの実装とSwaggerドキュメンテーションの更新
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_repository.go
  services/class_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#157 ToggleFavorite 機能の実装
  constants/error_messages.go
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#158 GoogleAuthCallbackメソッドの変更
  controllers/google_auth_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: ⏰ P1, 🔨 Refactor, 📬 API, 🆗 safe

#160 ユーザーロール管理機能の改善
  controllers/class_code_controller.go
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/role_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#162 ユーザーをクラスから削除する機能とSwaggerドキュメントの更新
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#163 HTTPメソッドのリクエストの変更
  main.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#168 クラス削除機能の実装と関連モデルの更新
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  models/class_board.go
  models/class_code.go
  models/class_schedule.go
  models/class_user.go
  repositories/class_repository.go
  services/class_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#169 クラス生成の時ユーザIDを追加
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_dto.go
  models/class.go
  services/class_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#172 ユーザーに不要な情報の送信を制限
  controllers/google_auth_controller.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#173 Modify Swagger docs for class
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⏰ P1, 🐞 BugFix, 📃 Docs, 🆗 safe

#175 クラス情報更新機能の実装とSwaggerドキュメントの更新
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_dto.go
  main.go
  repositories/class_repository.go
  services/class_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#176 WebSocket統合によるリアルタイムクラス機能の実装
  controllers/live_class_controller.go
  go.mod
  go.sum
  main.go
  services/live_class_service.go
Labels: ⏰ P1, ✨ Feature, 📬 API

#179 アクセストークン再発行機能の実装
  constants/error_messages.go
  controllers/google_auth_controller.go
  main.go
  services/google_auth_service.go
Labels: ⏰ P1, ✨ Feature, 🆗 safe

#180 クラス作成時にユーザーに管理者権限を付与する機能の追加
  repositories/class_user_repository.go
  services/class_service.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🆗 safe

#181 コメントアウトされた機能の一時的な削除
  main.go
Labels: 🌏 Deploy, 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#182 コメントアウトされた機能の一時的な削除
  main.go
Labels: 🌏 Deploy, 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#183 コメントアウトされた機能の一時的な削除
  controllers/live_class_controller.go
  go.mod
  go.sum
  services/live_class_service.go
Labels: 🌏 Deploy, 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#185 画面共有機能の実装と中間層ミドルウェアの構築
  controllers/live_class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
  middlewares/authentication_middleware.go
  services/live_class_service.go
Labels: ⏰ P1, ⚙ Setting, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#186 ライブクラスの画面共有機能の改善
  controllers/live_class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/live_class_service.go
Labels: ⏰ P1, 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#187 ♻️ HTTPステータスコードを定数で管理するリファクタリング
  controllers/live_class_controller.go
Labels: 🔨 Refactor, 📬 API

#189 リフレッシュトークンを要求するロジックの修正
  controllers/google_auth_controller.go
Labels: ⏰ P1, 🐞 BugFix, 📬 API, 🆗 safe

#191 チャット機能のバグ修正とSwaggerドキュメントの更新
  controllers/chat_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 📬 API, 🆗 safe

#192 アクセストークン再発行機能のSwaggerドキュメントの更新
  controllers/google_auth_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#194 クラス掲示板の画像アップロード処理とSwaggerドキュメントの修正
  controllers/class_board_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#195 アクセストークン再発行機能の修正
  controllers/google_auth_controller.go
  main.go
  services/google_auth_service.go
Labels: ⏰ P1, 🐞 BugFix, 🆗 safe

#198 新しいチャット機能とSwaggerドキュメントの更新
  controllers/chat_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/chat_service.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 📃 Docs, 🆗 safe

#200 ページネーション機能とSwaggerドキュメントの更新Feat/add pagination to class listing
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#201 トークンを使用して認証するミドルウェアの実装
  middlewares/authentication_middleware.go
Labels: ✨ Feature, 📬 API, ⏰ P2, 🆗 safe

#202 画面共有機能のルーティングエラー修正
  controllers/live_class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#204 クラススケジュール更新APIをPUTからPATCHに変更
  controllers/class_schedule_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#205 APIルートにおけるJWT認証ミドルウェア実装
  main.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 🆗 safe

#207 お気に入りクラスの取得処理を修正
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#208 トークンを使用して認証するミドルウェアの実装
  main.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 🆗 safe

#209 画面共有機能の強化とSwaggerドキュメントの更新
  controllers/live_class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
  repositories/class_user_repository.go
  services/live_class_service.go
Labels: ⏰ P1, ⚙ Setting, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#211 jwtペイロードキーの変更
  middlewares/authentication_middleware.go
  services/google_auth_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#213 ユーザー画像の取得問題を修正
  repositories/class_user_repository.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#214 jwtペイロードキーの変更によるアクセストークン再発行機能の修正
  services/google_auth_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#216 SwaggerにBearer Authenticationを実装
  controllers/attendance_controller.go
  controllers/chat_controller.go
  controllers/class_board_controller.go
  controllers/class_code_controller.go
  controllers/class_controller.go
  controllers/class_schedule_controller.go
  controllers/class_user_controller.go
  controllers/user_controller.go
  main.go
Labels: ⚙ Setting, ✨ Feature, 📃 Docs, ⏰ P2, 🆗 safe

#217 SwaggerにBearer Authenticationを実装
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⚙ Setting, ✨ Feature, 📃 Docs, ⏰ P2, 🆗 safe

#218 画面共有機能の実装
  controllers/live_class_controller.go
  main.go
  services/live_class_service.go
Labels: ⏰ P1, ⚙ Setting, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#219 [MIN-145] 管理者の画面共有機能の強化
  controllers/live_class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/live_class_service.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, 🆗 safe

#220 [MIN-145] 画面共有機能のWebRTC設定を強化
  main.go
Labels: ⏰ P1, ✨ Feature, 📬 API, 🆗 safe

#221 [MIN-145] 画面共有機能の最適化とストリーミングプロセスの統合
  controllers/live_class_controller.go
  services/live_class_service.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#222 [MIN-145] WebSocketからSocket.IOへの通信方式変更
  go.mod
  go.sum
  main.go
Labels: ⏰ P1, ⚙ Setting, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#223 [MIN-145] WebSocketとWebRTCの統合を最適化するリファクタリング
  main.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#224 [MIN-145] WebSocketのエンドポイントを追加
  main.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#228 [MIN-258] 🐛 チャットルーム削除機能の修正と404ハンドリングの改善
  controllers/chat_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/chat_service.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#230 [MIN-182] チャットAPIのレスポンス最適化とサービスロジックの改善
  controllers/chat_controller.go
  main.go
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#231 [MIN-182] チャット機能の細かい調整と新機能の実装
  services/chat_service.go
Labels: ⏰ P3, 🔨 Refactor, 📬 API, 🆗 safe

#232 [MIN-182] Swaggerドキュメントの全面的な更新
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 📃 Docs, ⏰ P2, 🆗 safe

#234 [MIN-273] 新規クラス作成時に自動でランダムクラスコードを生成する機能の実装
  main.go
  repositories/class_code_repository.go
  services/class_code_service.go
  services/class_service.go
Labels: ⏰ P3, 🐞 BugFix, 🔨 Refactor, 📬 API, 🆗 safe

#236 [MIN-274] ユーザー名検索機能とSwaggerドキュメントの追加
  controllers/user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/user_repository.go
  services/user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#238 [MIN-275] クラス作成機能にパスワードオプションを追加
  controllers/class_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dto/class_dto.go
  models/class_code.go
  services/class_service.go
Labels: 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#240 [MIN-276] クラス掲示板の更新通知機能
  controllers/class_board_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/class_board_service.go
Labels: ⏰ P3, ✨ Feature, 📬 API, 📃 Docs, 🆗 safe

#242 [MIN-182] ダイレクトメッセージ削除APIの実装とドキュメント更新
  controllers/chat_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  services/chat_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#244 ユーザー削除機能の実装
  controllers/user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/user_repository.go
  services/user_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#246 [MIN-281] ユーザー登録クラス検索機能
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_user_service.go
Labels: ⏰ P3, ✨ Feature, 📬 API, 📃 Docs, 🆗 safe
