Repository YJU-OKURA/project_minori-gin-deployment-repo, pull requests merged in 2024-05, with the labels that each got.

#250 データベース合併についての修正
  dto/class_user_dto.go
  models/class_user.go
  models/role.go
  repositories/class_user_repository.go
  repositories/role_repository.go
  repositories/user_repository.go
  services/class_service.go
  services/class_user_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#251 データベース合併についての修正
  controllers/class_code_controller.go
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#252 データベース合併についてのミドルウェアとマイグレーションの修正
  middlewares/authentication_middleware.go
  migration/migration.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#253 クラスユーザーレポジトリの修正
  repositories/class_user_repository.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#256 [MIN-290] クラス掲示板の検索機能の実装
  controllers/class_board_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  repositories/class_board_repository.go
  services/class_board_service.go
Labels: ✨ Feature, 📬 API, 📃 Docs, ⏰ P2

#257 [MIN-145] 画面共有のためのWebRTCロジックチェックを実装
  main.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#258 [MIN-145] Pion WebRTCライブラリをv4.0.0-beta.19に更新
  go.mod
  go.sum
Labels: ⚙ Setting, ⏰ P3, 🆗 safe

#259 UIDとCIDの有効性を検証するロジックを追加
  repositories/class_code_repository.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#261 [MIN-205] 無停止デプロイメントのためのDockerおよびCI/CD設定の最適化
  .github/workflows/cd.yml
  docker-compose.yml
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#262 [MIN-205] CI/CDワークフローにworkflow_dispatchを追加
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#263 [MIN-205] CDワークフローの作業ディレクトリ設定の最適化
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#264 [MIN-205] デプロイメントパスの誤りを修正
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#265 [MIN-205] CIワークフローのDockerビルドでキャッシュを無効に
  .github/workflows/ci.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#266 [MIN-205] Dockerfileに`go mod tidy`を追加
  Dockerfile
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#267 [MIN-205] EC2デプロイメントコマンドの更新
  .github/workflows/cd.yml
Labels: ⏰ P1, 🌏 Deploy, 🐞 BugFix, 🔨 Refactor, 🆗 safe

#268 クラス生成時入力される情報の追加
  services/class_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#270 クラス内の基本的なニックネームの設定
  repositories/user_repository.go
  services/class_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#271 不足のアーギュメントの追加
  main.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#272 [MIN-145] ✨ 画面共有機能のバックエンド実装
  main.go
Labels: ⏰ P1, ✨ Feature, 🔨 Refactor, 📬 API, 🆗 safe

#274 GetUserClassesByRoleの修正
  controllers/class_user_controller.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#275 roleに関するルーティングの修正
  main.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#276 Swaggerのコメントの修正
  controllers/class_user_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#279 ルーティングのパラメートルの修正
  main.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#281 GetClassMembersメッソドのルーティングの修正
  main.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🆗 safe

#280 クラスコードによるクラス加入申し込みの実装
  controllers/class_code_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  repositories/class_user_repository.go
  services/class_code_service.go
  services/class_user_service.go
Labels: ✨ Feature, 🔨 Refactor, 📬 API, 📃 Docs, ⏰ P2, 🆗 safe

#282 [MIN-291] CORS設定の更新：AWSロードバランサーからのアクセスを許可
  main.go
Labels: ⏰ P1, ⚙ Setting, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#283 [MIN-291] 動的なオリジン検証をサポートするCORSミドルウェアの更新
  main.go
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 🆗 safe

#284 [MIN-291] minoriedu.comに対するCORS設定の追加
  main.go
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 📬 API, 🆗 safe

#285 [MIN-291] ECSに対するCORS設定の追加
  main.go
Labels: ⏰ P1, 🌏 Deploy, 🔨 Refactor, 📬 API, 🆗 safe

#286 [MIN-291] CORSのOPTIONSメソッドチェックをコメントアウトして403エラーを修正
  main.go
Labels: ⏰ P1, 🐞 BugFix, 🔨 Refactor, 📬 API, 🆗 safe

#287 CORS問題の解決
  main.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🥰 Accessibility, 🆗 safe

#288 CORSによるレスポンスの修正
  main.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🥰 Accessibility, 🆗 safe

#289 ignorePathの修正
  main.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🥰 Accessibility, 🆗 safe

#290 リクエストパスのプレフィックスをチェックするロジックの修正
  main.go
Labels: 🐞 BugFix, 📬 API, ⏰ P2, 🥰 Accessibility, 🆗 safe

#291 [MIN-292] Swaggerのサマリーとパラメーターの説明を更新
  controllers/chat_controller.go
  controllers/class_controller.go
  controllers/class_user_controller.go
  controllers/google_auth_controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: ⏰ P3, 🔨 Refactor, 📃 Docs, 🆗 safe

#293 [MIN-293] Dockerfileの最適化
  Dockerfile
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#294 [MIN-293] `ko`によるGoアプリケーションのビルド統合
  .github/workflows/ci.yml
  .ko.yaml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#295 [MIN-293] Goバージョンを1.21に更新してkoの互換性を確保
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#296 [MIN-293] GitHub Actionsのビルド時間最適化および最新ガイドライン適用
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#297 [MIN-293] Goバージョンを1.22にアップデートし、CIワークフローを最適化
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#298 [MIN-293] Docker Image CIワークフローにkoインストールとPATH設定を追加
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🔨 Refactor, ⏰ P2, 🆗 safe

#300 クラス情報にクラスコードを追加
  controllers/class_controller.go
  repositories/class_code_repository.go
  services/class_service.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe

#302 initializeSwaggerメッソドの呼び順番の修正
  main.go
Labels: 🔨 Refactor, 📬 API, ⏰ P2, 🆗 safe
